apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        env: 
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom: 
            secretKeyRef: 
              name: mongo-secret
              key: mongo-user 
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mongo-secret
              key: mongo-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom: 
            configMapKeyRef: 
              name: mongo-config
              key: mongo-url
        - name: ME_CONFIG_BASICAUTH_USERNAME
          valueFrom: 
            secretKeyRef: 
              name: mongo-secret
              key: mongo-user
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mongo-secret
              key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30200
    protocol: TCP
